CREATE TABLE IF NOT EXISTS pohon_kinerja
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,
    parent_id      BIGINT,
    nama_pohon     VARCHAR(255) NOT NULL,
    keterangan     TEXT,
    tahun          VARCHAR(4)   NOT NULL,
    jenis_pohon    VARCHAR(50)  NOT NULL,
    level_pohon    INT          NOT NULL,
    kode_opd       VARCHAR(50),
    kode_pemda     VARCHAR(50),
    status         VARCHAR(50),
    CONSTRAINT fk_pohon_parent FOREIGN KEY (parent_id) REFERENCES pohon_kinerja (id) ON DELETE CASCADE
);

CREATE INDEX idx_pohon_parent ON pohon_kinerja(parent_id);
CREATE INDEX idx_pohon_tahun ON pohon_kinerja(tahun);