CREATE TABLE IF NOT EXISTS indikator
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,
    pohon_kinerja_id BIGINT       NOT NULL,
    indikator        VARCHAR(255) NOT NULL,
    keterangan       TEXT,
    tahun            VARCHAR(4)   NOT NULL,
    CONSTRAINT fk_indikator_pohon FOREIGN KEY (pohon_kinerja_id) REFERENCES pohon_kinerja (id) ON DELETE CASCADE
);