CREATE TABLE IF NOT EXISTS target
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,
    indikator_id BIGINT     NOT NULL,
    nilai        DOUBLE PRECISION,
    satuan       VARCHAR(50),
    tahun        VARCHAR(4) NOT NULL,
    CONSTRAINT fk_target_indikator FOREIGN KEY (indikator_id) REFERENCES indikator (id) ON DELETE CASCADE
);