-- =================================================================================
-- FLYWAY V9: SEED TEMATIK ROOT OPD TAHUN 2026
-- =================================================================================
-- Tujuan: Generate root Tematik (level 0) untuk semua OPD tahun 2026
-- Total: 88 OPD
-- ID Range: 107 - 194 (auto-generated by sequence)
-- =================================================================================

INSERT INTO pohon_kinerja (parent_id, nama_pohon, keterangan, tahun, jenis_pohon, level_pohon, kode_opd, kode_pemda, status) VALUES
(NULL, 'Pohon Kinerja Dinas Pendidikan dan Kebudayaan', 'Perencanaan kinerja Dinas Pendidikan dan Kebudayaan tahun 2026', 2026, 'TEMATIK', 0, '1.01.2.22.0.00.01.0000', NULL, 'DRAFT'),
(NULL, 'Pohon Kinerja Dinas Kesehatan', 'Perencanaan kinerja Dinas Kesehatan tahun 2026', 2026, 'TEMATIK', 0, '1.02.0.00.0.00.01.0000', NULL, 'DRAFT'),
(NULL, 'Pohon Kinerja Puskesmas Kebonsari', 'Perencanaan kinerja Puskesmas Kebonsari tahun 2026', 2026, 'TEMATIK', 0, '1.02.0.00.0.00.01.0001', NULL, 'DRAFT'),
(NULL, 'Pohon Kinerja Puskesmas Gantrung', 'Perencanaan kinerja Puskesmas Gantrung tahun 2026', 2026, 'TEMATIK', 0, '1.02.0.00.0.00.01.0002', NULL, 'DRAFT'),
(NULL, 'Pohon Kinerja Puskesmas Geger', 'Perencanaan kinerja Puskesmas Geger tahun 2026', 2026, 'TEMATIK', 0, '1.02.0.00.0.00.01.0003', NULL, 'DRAFT'),
(NULL, 'Pohon Kinerja Puskesmas Kaibon', 'Perencanaan kinerja Puskesmas Kaibon tahun 2026', 2026, 'TEMATIK', 0, '1.02.0.00.0.00.01.0004', NULL, 'DRAFT'),
(NULL, 'Pohon Kinerja Puskesmas Mlilir', 'Perencanaan kinerja Puskesmas Mlilir tahun 2026', 2026, 'TEMATIK', 0, '1.02.0.00.0.00.01.0005', NULL, 'DRAFT'),
(NULL, 'Pohon Kinerja Puskesmas Bangunsari', 'Perencanaan kinerja Puskesmas Bangunsari tahun 2026', 2026, 'TEMATIK', 0, '1.02.0.00.0.00.01.0006', NULL, 'DRAFT'),
(NULL, 'Pohon Kinerja Puskesmas Dagangan', 'Perencanaan kinerja Puskesmas Dagangan tahun 2026', 2026, 'TEMATIK', 0, '1.02.0.00.0.00.01.0007', NULL, 'DRAFT'),
(NULL, 'Pohon Kinerja Puskesmas Jetis', 'Perencanaan kinerja Puskesmas Jetis tahun 2026', 2026, 'TEMATIK', 0, '1.02.0.00.0.00.01.0008', NULL, 'DRAFT'),
(NULL, 'Pohon Kinerja Puskesmas Wungu', 'Perencanaan kinerja Puskesmas Wungu tahun 2026', 2026, 'TEMATIK', 0, '1.02.0.00.0.00.01.0009', NULL, 'DRAFT'),
(NULL, 'Pohon Kinerja Puskesmas Mojopurno', 'Perencanaan kinerja Puskesmas Mojopurno tahun 2026', 2026, 'TEMATIK', 0, '1.02.0.00.0.00.01.0010', NULL, 'DRAFT'),
(NULL, 'Pohon Kinerja Puskesmas Kare', 'Perencanaan kinerja Puskesmas Kare tahun 2026', 2026, 'TEMATIK', 0, '1.02.0.00.0.00.01.0011', NULL, 'DRAFT'),
(NULL, 'Pohon Kinerja Puskesmas Gemarang', 'Perencanaan kinerja Puskesmas Gemarang tahun 2026', 2026, 'TEMATIK', 0, '1.02.0.00.0.00.01.0012', NULL, 'DRAFT'),
(NULL, 'Pohon Kinerja Puskesmas Saradan', 'Perencanaan kinerja Puskesmas Saradan tahun 2026', 2026, 'TEMATIK', 0, '1.02.0.00.0.00.01.0013', NULL, 'DRAFT'),
(NULL, 'Pohon Kinerja Puskesmas Sumbersari', 'Perencanaan kinerja Puskesmas Sumbersari tahun 2026', 2026, 'TEMATIK', 0, '1.02.0.00.0.00.01.0014', NULL, 'DRAFT'),
(NULL, 'Pohon Kinerja Puskesmas Pilangkenceng', 'Perencanaan kinerja Puskesmas Pilangkenceng tahun 2026', 2026, 'TEMATIK', 0, '1.02.0.00.0.00.01.0015', NULL, 'DRAFT'),
(NULL, 'Pohon Kinerja Puskesmas Krebet', 'Perencanaan kinerja Puskesmas Krebet tahun 2026', 2026, 'TEMATIK', 0, '1.02.0.00.0.00.01.0016', NULL, 'DRAFT'),
(NULL, 'Pohon Kinerja Puskesmas Mejayan', 'Perencanaan kinerja Puskesmas Mejayan tahun 2026', 2026, 'TEMATIK', 0, '1.02.0.00.0.00.01.0017', NULL, 'DRAFT'),
(NULL, 'Pohon Kinerja Puskesmas Klecorejo', 'Perencanaan kinerja Puskesmas Klecorejo tahun 2026', 2026, 'TEMATIK', 0, '1.02.0.00.0.00.01.0018', NULL, 'DRAFT'),
(NULL, 'Pohon Kinerja Puskesmas Wonoasri', 'Perencanaan kinerja Puskesmas Wonoasri tahun 2026', 2026, 'TEMATIK', 0, '1.02.0.00.0.00.01.0019', NULL, 'DRAFT'),
(NULL, 'Pohon Kinerja Puskesmas Balerejo', 'Perencanaan kinerja Puskesmas Balerejo tahun 2026', 2026, 'TEMATIK', 0, '1.02.0.00.0.00.01.0020', NULL, 'DRAFT'),
(NULL, 'Pohon Kinerja Puskesmas Simo', 'Perencanaan kinerja Puskesmas Simo tahun 2026', 2026, 'TEMATIK', 0, '1.02.0.00.0.00.01.0021', NULL, 'DRAFT'),
(NULL, 'Pohon Kinerja Puskesmas Madiun', 'Perencanaan kinerja Puskesmas Madiun tahun 2026', 2026, 'TEMATIK', 0, '1.02.0.00.0.00.01.0022', NULL, 'DRAFT'),
(NULL, 'Pohon Kinerja Puskesmas Dimong', 'Perencanaan kinerja Puskesmas Dimong tahun 2026', 2026, 'TEMATIK', 0, '1.02.0.00.0.00.01.0023', NULL, 'DRAFT'),
(NULL, 'Pohon Kinerja Puskesmas Sawahan', 'Perencanaan kinerja Puskesmas Sawahan tahun 2026', 2026, 'TEMATIK', 0, '1.02.0.00.0.00.01.0024', NULL, 'DRAFT'),
(NULL, 'Pohon Kinerja Puskesmas Klagenserut', 'Perencanaan kinerja Puskesmas Klagenserut tahun 2026', 2026, 'TEMATIK', 0, '1.02.0.00.0.00.01.0025', NULL, 'DRAFT'),
(NULL, 'Pohon Kinerja Puskesmas Jiwan', 'Perencanaan kinerja Puskesmas Jiwan tahun 2026', 2026, 'TEMATIK', 0, '1.02.0.00.0.00.01.0026', NULL, 'DRAFT'),
(NULL, 'Pohon Kinerja RSUD Caruban', 'Perencanaan kinerja RSUD Caruban tahun 2026', 2026, 'TEMATIK', 0, '1.02.0.00.0.00.01.0027', NULL, 'DRAFT'),
(NULL, 'Pohon Kinerja RSUD Dolopo', 'Perencanaan kinerja RSUD Dolopo tahun 2026', 2026, 'TEMATIK', 0, '1.02.0.00.0.00.01.0028', NULL, 'DRAFT'),
(NULL, 'Pohon Kinerja Dinas Pekerjaan Umum dan Penataan Ruang', 'Perencanaan kinerja Dinas Pekerjaan Umum dan Penataan Ruang tahun 2026', 2026, 'TEMATIK', 0, '1.03.0.00.0.00.01.0000', NULL, 'DRAFT'),
(NULL, 'Pohon Kinerja Dinas Perumahan dan Kawasan Permukiman', 'Perencanaan kinerja Dinas Perumahan dan Kawasan Permukiman tahun 2026', 2026, 'TEMATIK', 0, '1.04.2.10.0.00.01.0000', NULL, 'DRAFT'),
(NULL, 'Pohon Kinerja Satuan Polisi Pamong Praja dan Pemadam Kebakaran', 'Perencanaan kinerja Satuan Polisi Pamong Praja dan Pemadam Kebakaran tahun 2026', 2026, 'TEMATIK', 0, '1.05.0.00.0.00.02.0000', NULL, 'DRAFT'),
(NULL, 'Pohon Kinerja Badan Penanggulangan Bencana Daerah', 'Perencanaan kinerja Badan Penanggulangan Bencana Daerah tahun 2026', 2026, 'TEMATIK', 0, '1.05.0.00.0.00.03.0000', NULL, 'DRAFT'),
(NULL, 'Pohon Kinerja Dinas Sosial', 'Perencanaan kinerja Dinas Sosial tahun 2026', 2026, 'TEMATIK', 0, '1.06.0.00.0.00.01.0000', NULL, 'DRAFT'),
(NULL, 'Pohon Kinerja Dinas Tenaga Kerja dan Perindustrian', 'Perencanaan kinerja Dinas Tenaga Kerja dan Perindustrian tahun 2026', 2026, 'TEMATIK', 0, '2.07.3.31.3.32.01.0000', NULL, 'DRAFT'),
(NULL, 'Pohon Kinerja Dinas Ketahanan Pangan dan Peternakan', 'Perencanaan kinerja Dinas Ketahanan Pangan dan Peternakan tahun 2026', 2026, 'TEMATIK', 0, '2.09.3.27.0.00.01.0000', NULL, 'DRAFT'),
(NULL, 'Pohon Kinerja Dinas Lingkungan Hidup', 'Perencanaan kinerja Dinas Lingkungan Hidup tahun 2026', 2026, 'TEMATIK', 0, '2.11.0.00.0.00.01.0000', NULL, 'DRAFT'),
(NULL, 'Pohon Kinerja Dinas Kependudukan dan Pencatatan Sipil', 'Perencanaan kinerja Dinas Kependudukan dan Pencatatan Sipil tahun 2026', 2026, 'TEMATIK', 0, '2.12.0.00.0.00.01.0000', NULL, 'DRAFT'),
(NULL, 'Pohon Kinerja Dinas Pemberdayaan Masyarakat dan Desa', 'Perencanaan kinerja Dinas Pemberdayaan Masyarakat dan Desa tahun 2026', 2026, 'TEMATIK', 0, '2.13.0.00.0.00.01.0000', NULL, 'DRAFT'),
(NULL, 'Pohon Kinerja Dinas Pengendalian Penduduk dan Keluarga Berencana, Pemberdayaan Perempuan dan Perlindungan Anak', 'Perencanaan kinerja Dinas Pengendalian Penduduk dan Keluarga Berencana, Pemberdayaan Perempuan dan Perlindungan Anak tahun 2026', 2026, 'TEMATIK', 0, '2.14.2.08.0.00.01.0000', NULL, 'DRAFT'),
(NULL, 'Pohon Kinerja Dinas Perhubungan', 'Perencanaan kinerja Dinas Perhubungan tahun 2026', 2026, 'TEMATIK', 0, '2.15.0.00.0.00.01.0000', NULL, 'DRAFT'),
(NULL, 'Pohon Kinerja Dinas Komunikasi dan Informatika', 'Perencanaan kinerja Dinas Komunikasi dan Informatika tahun 2026', 2026, 'TEMATIK', 0, '2.16.2.20.2.21.01.0000', NULL, 'DRAFT'),
(NULL, 'Pohon Kinerja Dinas Perdagangan, Koperasi dan Usaha Mikro', 'Perencanaan kinerja Dinas Perdagangan, Koperasi dan Usaha Mikro tahun 2026', 2026, 'TEMATIK', 0, '2.17.3.30.0.00.01.0000', NULL, 'DRAFT'),
(NULL, 'Pohon Kinerja Dinas Penanaman Modal dan Pelayanan Terpadu Satu Pintu', 'Perencanaan kinerja Dinas Penanaman Modal dan Pelayanan Terpadu Satu Pintu tahun 2026', 2026, 'TEMATIK', 0, '2.18.0.00.0.00.01.0000', NULL, 'DRAFT'),
(NULL, 'Pohon Kinerja Dinas Pariwisata Pemuda dan Olah Raga', 'Perencanaan kinerja Dinas Pariwisata Pemuda dan Olah Raga tahun 2026', 2026, 'TEMATIK', 0, '2.19.3.26.0.00.01.0000', NULL, 'DRAFT'),
(NULL, 'Pohon Kinerja Dinas Perpustakaan dan Kearsipan', 'Perencanaan kinerja Dinas Perpustakaan dan Kearsipan tahun 2026', 2026, 'TEMATIK', 0, '2.23.2.24.0.00.01.0000', NULL, 'DRAFT'),
(NULL, 'Pohon Kinerja Dinas Pertanian dan Perikanan', 'Perencanaan kinerja Dinas Pertanian dan Perikanan tahun 2026', 2026, 'TEMATIK', 0, '3.27.3.25.0.00.01.0000', NULL, 'DRAFT'),
(NULL, 'Pohon Kinerja Sekretariat Daerah', 'Perencanaan kinerja Sekretariat Daerah tahun 2026', 2026, 'TEMATIK', 0, '4.01.5.06.0.00.03.0000', NULL, 'DRAFT'),
(NULL, 'Pohon Kinerja Bagian Administrasi Pemerintahan', 'Perencanaan kinerja Bagian Administrasi Pemerintahan tahun 2026', 2026, 'TEMATIK', 0, '4.01.5.06.0.00.03.0001', NULL, 'DRAFT'),
(NULL, 'Pohon Kinerja Bagian Hukum', 'Perencanaan kinerja Bagian Hukum tahun 2026', 2026, 'TEMATIK', 0, '4.01.5.06.0.00.03.0002', NULL, 'DRAFT'),
(NULL, 'Pohon Kinerja Bagian Pengadaan Barang dan Jasa', 'Perencanaan kinerja Bagian Pengadaan Barang dan Jasa tahun 2026', 2026, 'TEMATIK', 0, '4.01.5.06.0.00.03.0003', NULL, 'DRAFT'),
(NULL, 'Pohon Kinerja Bagian Kesejahteraan Rakyat', 'Perencanaan kinerja Bagian Kesejahteraan Rakyat tahun 2026', 2026, 'TEMATIK', 0, '4.01.5.06.0.00.03.0005', NULL, 'DRAFT'),
(NULL, 'Pohon Kinerja Bagian Perekonomian', 'Perencanaan kinerja Bagian Perekonomian tahun 2026', 2026, 'TEMATIK', 0, '4.01.5.06.0.00.03.0006', NULL, 'DRAFT'),
(NULL, 'Pohon Kinerja Bagian Umum', 'Perencanaan kinerja Bagian Umum tahun 2026', 2026, 'TEMATIK', 0, '4.01.5.06.0.00.03.0007', NULL, 'DRAFT'),
(NULL, 'Pohon Kinerja Bagian Organisasi', 'Perencanaan kinerja Bagian Organisasi tahun 2026', 2026, 'TEMATIK', 0, '4.01.5.06.0.00.03.0008', NULL, 'DRAFT'),
(NULL, 'Pohon Kinerja Bagian Protokol dan Komunikasi Pimpinan', 'Perencanaan kinerja Bagian Protokol dan Komunikasi Pimpinan tahun 2026', 2026, 'TEMATIK', 0, '4.01.5.06.0.00.03.0009', NULL, 'DRAFT'),
(NULL, 'Pohon Kinerja Bagian Administrasi Pembangunan', 'Perencanaan kinerja Bagian Administrasi Pembangunan tahun 2026', 2026, 'TEMATIK', 0, '4.01.5.06.0.00.03.0010', NULL, 'DRAFT'),
(NULL, 'Pohon Kinerja Sekretariat Dewan Perwakilan Rakyat Daerah', 'Perencanaan kinerja Sekretariat Dewan Perwakilan Rakyat Daerah tahun 2026', 2026, 'TEMATIK', 0, '4.02.0.00.0.00.04.0000', NULL, 'DRAFT'),
(NULL, 'Pohon Kinerja Badan Perencanaan Pembangunan Riset, dan Inovasi Daerah', 'Perencanaan kinerja Badan Perencanaan Pembangunan Riset, dan Inovasi Daerah tahun 2026', 2026, 'TEMATIK', 0, '5.01.5.05.0.00.01.0000', NULL, 'DRAFT'),
(NULL, 'Pohon Kinerja Badan Pengelolaan Keuangan dan Aset Daerah', 'Perencanaan kinerja Badan Pengelolaan Keuangan dan Aset Daerah tahun 2026', 2026, 'TEMATIK', 0, '5.02.0.00.0.00.01.0000', NULL, 'DRAFT'),
(NULL, 'Pohon Kinerja Badan Pendapatan Daerah', 'Perencanaan kinerja Badan Pendapatan Daerah tahun 2026', 2026, 'TEMATIK', 0, '5.02.0.00.0.00.02.0000', NULL, 'DRAFT'),
(NULL, 'Pohon Kinerja Badan Kepegawaian dan Pengembangan Sumber Daya Manusia', 'Perencanaan kinerja Badan Kepegawaian dan Pengembangan Sumber Daya Manusia tahun 2026', 2026, 'TEMATIK', 0, '5.03.5.04.0.00.01.0000', NULL, 'DRAFT'),
(NULL, 'Pohon Kinerja Inspektorat', 'Perencanaan kinerja Inspektorat tahun 2026', 2026, 'TEMATIK', 0, '6.01.0.00.0.00.01.0000', NULL, 'DRAFT'),
(NULL, 'Pohon Kinerja Kecamatan Balerejo', 'Perencanaan kinerja Kecamatan Balerejo tahun 2026', 2026, 'TEMATIK', 0, '7.01.0.00.0.00.05.0000', NULL, 'DRAFT'),
(NULL, 'Pohon Kinerja Kecamatan Dagangan', 'Perencanaan kinerja Kecamatan Dagangan tahun 2026', 2026, 'TEMATIK', 0, '7.01.0.00.0.00.06.0000', NULL, 'DRAFT'),
(NULL, 'Pohon Kinerja Kecamatan Dolopo', 'Perencanaan kinerja Kecamatan Dolopo tahun 2026', 2026, 'TEMATIK', 0, '7.01.0.00.0.00.07.0000', NULL, 'DRAFT'),
(NULL, 'Pohon Kinerja Kelurahan Bangunsari Dolopo', 'Perencanaan kinerja Kelurahan Bangunsari Dolopo tahun 2026', 2026, 'TEMATIK', 0, '7.01.0.00.0.00.07.0001', NULL, 'DRAFT'),
(NULL, 'Pohon Kinerja Kelurahan Mlilir', 'Perencanaan kinerja Kelurahan Mlilir tahun 2026', 2026, 'TEMATIK', 0, '7.01.0.00.0.00.07.0002', NULL, 'DRAFT'),
(NULL, 'Pohon Kinerja Kecamatan Geger', 'Perencanaan kinerja Kecamatan Geger tahun 2026', 2026, 'TEMATIK', 0, '7.01.0.00.0.00.08.0000', NULL, 'DRAFT'),
(NULL, 'Pohon Kinerja Kecamatan Gemarang', 'Perencanaan kinerja Kecamatan Gemarang tahun 2026', 2026, 'TEMATIK', 0, '7.01.0.00.0.00.09.0000', NULL, 'DRAFT'),
(NULL, 'Pohon Kinerja Kecamatan Jiwan', 'Perencanaan kinerja Kecamatan Jiwan tahun 2026', 2026, 'TEMATIK', 0, '7.01.0.00.0.00.10.0000', NULL, 'DRAFT'),
(NULL, 'Pohon Kinerja Kecamatan Kebonsari', 'Perencanaan kinerja Kecamatan Kebonsari tahun 2026', 2026, 'TEMATIK', 0, '7.01.0.00.0.00.11.0000', NULL, 'DRAFT'),
(NULL, 'Pohon Kinerja Kecamatan Kare', 'Perencanaan kinerja Kecamatan Kare tahun 2026', 2026, 'TEMATIK', 0, '7.01.0.00.0.00.12.0000', NULL, 'DRAFT'),
(NULL, 'Pohon Kinerja Kecamatan Madiun', 'Perencanaan kinerja Kecamatan Madiun tahun 2026', 2026, 'TEMATIK', 0, '7.01.0.00.0.00.13.0000', NULL, 'DRAFT'),
(NULL, 'Pohon Kinerja Kelurahan Nglames', 'Perencanaan kinerja Kelurahan Nglames tahun 2026', 2026, 'TEMATIK', 0, '7.01.0.00.0.00.13.0001', NULL, 'DRAFT'),
(NULL, 'Pohon Kinerja Kecamatan Mejayan', 'Perencanaan kinerja Kecamatan Mejayan tahun 2026', 2026, 'TEMATIK', 0, '7.01.0.00.0.00.14.0000', NULL, 'DRAFT'),
(NULL, 'Pohon Kinerja Kelurahan Bangunsari Mejayan', 'Perencanaan kinerja Kelurahan Bangunsari Mejayan tahun 2026', 2026, 'TEMATIK', 0, '7.01.0.00.0.00.14.0001', NULL, 'DRAFT'),
(NULL, 'Pohon Kinerja Kelurahan Krajan', 'Perencanaan kinerja Kelurahan Krajan tahun 2026', 2026, 'TEMATIK', 0, '7.01.0.00.0.00.14.0002', NULL, 'DRAFT'),
(NULL, 'Pohon Kinerja Kelurahan Pandean', 'Perencanaan kinerja Kelurahan Pandean tahun 2026', 2026, 'TEMATIK', 0, '7.01.0.00.0.00.14.0003', NULL, 'DRAFT'),
(NULL, 'Pohon Kinerja Kecamatan Pilangkenceng', 'Perencanaan kinerja Kecamatan Pilangkenceng tahun 2026', 2026, 'TEMATIK', 0, '7.01.0.00.0.00.15.0000', NULL, 'DRAFT'),
(NULL, 'Pohon Kinerja Kecamatan Sawahan', 'Perencanaan kinerja Kecamatan Sawahan tahun 2026', 2026, 'TEMATIK', 0, '7.01.0.00.0.00.16.0000', NULL, 'DRAFT'),
(NULL, 'Pohon Kinerja Kecamatan Saradan', 'Perencanaan kinerja Kecamatan Saradan tahun 2026', 2026, 'TEMATIK', 0, '7.01.0.00.0.00.17.0000', NULL, 'DRAFT'),
(NULL, 'Pohon Kinerja Kecamatan Wungu', 'Perencanaan kinerja Kecamatan Wungu tahun 2026', 2026, 'TEMATIK', 0, '7.01.0.00.0.00.18.0000', NULL, 'DRAFT'),
(NULL, 'Pohon Kinerja Kelurahan Wungu', 'Perencanaan kinerja Kelurahan Wungu tahun 2026', 2026, 'TEMATIK', 0, '7.01.0.00.0.00.18.0001', NULL, 'DRAFT'),
(NULL, 'Pohon Kinerja Kelurahan Munggut', 'Perencanaan kinerja Kelurahan Munggut tahun 2026', 2026, 'TEMATIK', 0, '7.01.0.00.0.00.18.0002', NULL, 'DRAFT'),
(NULL, 'Pohon Kinerja Kecamatan Wonoasri', 'Perencanaan kinerja Kecamatan Wonoasri tahun 2026', 2026, 'TEMATIK', 0, '7.01.0.00.0.00.19.0000', NULL, 'DRAFT'),
(NULL, 'Pohon Kinerja Badan Kesatuan Bangsa dan Politik', 'Perencanaan kinerja Badan Kesatuan Bangsa dan Politik tahun 2026', 2026, 'TEMATIK', 0, '8.01.0.00.0.00.01.0000', NULL, 'DRAFT');

-- =================================================================================
-- RESET SEQUENCE
-- Ensure next INSERT gets correct ID
-- =================================================================================
SELECT setval('pohon_kinerja_id_seq', (SELECT MAX(id) FROM pohon_kinerja));

-- =================================================================================
-- SUMMARY V9:
-- - Total OPD: 88
-- - ID Range: 107 - 194 (auto-generated)
-- - Year: 2026
-- - Type: TEMATIK (Level 0)
-- - Status: DRAFT
-- - kode_opd: Filled
-- - kode_pemda: NULL
-- =================================================================================
